### ISSUE TITLE
Invalid input: root must be an object

### ISSUE THREAD

**Issue by Vladdy88** [Exploriment/hcloud-php#2]
I tried to implement the reboot and shutdown method from HetznerCloud\Servers but I keep getting the error : `exception 'Exploriment\HetznerCloud\Exceptions\ApiInvalidInput' with message 'invalid input: root must be an object' in /home/hvbeta/public_html/modules/addons/hv_hetzner/vendor/exploriment/hcloud-php/src/Http.php:123`
I tried to check the input of the request method from Http class and it looks ok :
```
string(6) "597685" string(31) "servers/597685/actions/shutdown" 
array(0) { } 
array(0) { } 
```
I also tried the API from Hetzner directly with curl and it works, so the problem must be somewhere at the method that sends the request, but I cannot figure out where.

**Comment by dyhli** [comment]
Should be fixed!

**Comment by Vladdy88** [comment]
Yes, it works now! Thank you again!
