### ISSUE TITLE
Servers::rebuild not returning new password

### ISSUE THREAD

**Issue by Vladdy88** [Exploriment/hcloud-php#5]
I have tested the Servers::rebuild method and the response of it is an Action object that has no root password and don't allow getRootPassword() method.

The public static function rebuild($id, $image) method from the final class Servers uses the trait Actionable action() method that returns only new Action($response->action), but the new root password is in $response->root_password.

Thank you!

**Comment by dyhli** [comment]
Fixed in version 1.1.2. Thank you.
